namespace Quadridge2.Migrations
{
    using System;
    using System.Data.Entity.Migrations;
    
    public partial class PopulateCountry : DbMigration
    {
        public override void Up()
        {
            Sql("INSERT INTO Countries VALUES ('AF', 'Afghanistan')");
            Sql("INSERT INTO Countries VALUES ('AL', 'Albania')");
            Sql("INSERT INTO Countries VALUES ('DZ', 'Algeria')");
            Sql("INSERT INTO Countries VALUES ('DS', 'American Samoa')");
            Sql("INSERT INTO Countries VALUES ('AD', 'Andorra')");
            Sql("INSERT INTO Countries VALUES ('AO', 'Angola')");
            Sql("INSERT INTO Countries VALUES ('AI', 'Anguilla')");
            Sql("INSERT INTO Countries VALUES ('AQ', 'Antarctica')");
            Sql("INSERT INTO Countries VALUES ('AG', 'Antigua and Barbuda')");
            Sql("INSERT INTO Countries VALUES ('AR', 'Argentina')");
            Sql("INSERT INTO Countries VALUES ('AM', 'Armenia')");
            Sql("INSERT INTO Countries VALUES ('AW', 'Aruba')");
            Sql("INSERT INTO Countries VALUES ('AU', 'Australia')");
            Sql("INSERT INTO Countries VALUES ('AT', 'Austria')");
            Sql("INSERT INTO Countries VALUES ('AZ', 'Azerbaijan')");
            Sql("INSERT INTO Countries VALUES ('BS', 'Bahamas')");
            Sql("INSERT INTO Countries VALUES ('BH', 'Bahrain')");
            Sql("INSERT INTO Countries VALUES ('BD', 'Bangladesh')");
            Sql("INSERT INTO Countries VALUES ('BB', 'Barbados')");
            Sql("INSERT INTO Countries VALUES ('BY', 'Belarus')");
            Sql("INSERT INTO Countries VALUES ('BE', 'Belgium')");
            Sql("INSERT INTO Countries VALUES ('BZ', 'Belize')");
            Sql("INSERT INTO Countries VALUES ('BJ', 'Benin')");
            Sql("INSERT INTO Countries VALUES ('BM', 'Bermuda')");
            Sql("INSERT INTO Countries VALUES ('BT', 'Bhutan')");
            Sql("INSERT INTO Countries VALUES ('BO', 'Bolivia')");
            Sql("INSERT INTO Countries VALUES ('BA', 'Bosnia and Herzegovina')");
            Sql("INSERT INTO Countries VALUES ('BW', 'Botswana')");
            Sql("INSERT INTO Countries VALUES ('BV', 'Bouvet Island')");
            Sql("INSERT INTO Countries VALUES ('BR', 'Brazil')");
            Sql("INSERT INTO Countries VALUES ('IO', 'British Indian Ocean Territory')");
            Sql("INSERT INTO Countries VALUES ('BN', 'Brunei Darussalam')");
            Sql("INSERT INTO Countries VALUES ('BG', 'Bulgaria')");
            Sql("INSERT INTO Countries VALUES ('BF', 'Burkina Faso')");
            Sql("INSERT INTO Countries VALUES ('BI', 'Burundi')");
            Sql("INSERT INTO Countries VALUES ('KH', 'Cambodia')");
            Sql("INSERT INTO Countries VALUES ('CM', 'Cameroon')");
            Sql("INSERT INTO Countries VALUES ('CA', 'Canada')");
            Sql("INSERT INTO Countries VALUES ('CV', 'Cape Verde')");
            Sql("INSERT INTO Countries VALUES ('KY', 'Cayman Islands')");
            Sql("INSERT INTO Countries VALUES ('CF', 'Central African Republic')");
            Sql("INSERT INTO Countries VALUES ('TD', 'Chad')");
            Sql("INSERT INTO Countries VALUES ('CL', 'Chile')");
            Sql("INSERT INTO Countries VALUES ('CN', 'China')");
            Sql("INSERT INTO Countries VALUES ('CX', 'Christmas Island')");
            Sql("INSERT INTO Countries VALUES ('CC', 'Cocos (Keeling) Islands')");
            Sql("INSERT INTO Countries VALUES ('CO', 'Colombia')");
            Sql("INSERT INTO Countries VALUES ('KM', 'Comoros')");
            Sql("INSERT INTO Countries VALUES ('CG', 'Congo')");
            Sql("INSERT INTO Countries VALUES ('CK', 'Cook Islands')");
            Sql("INSERT INTO Countries VALUES ('CR', 'Costa Rica')");
            Sql("INSERT INTO Countries VALUES ('HR', 'Croatia (Hrvatska)')");
            Sql("INSERT INTO Countries VALUES ('CU', 'Cuba')");
            Sql("INSERT INTO Countries VALUES ('CY', 'Cyprus')");
            Sql("INSERT INTO Countries VALUES ('CZ', 'Czech Republic')");
            Sql("INSERT INTO Countries VALUES ('DK', 'Denmark')");
            Sql("INSERT INTO Countries VALUES ('DJ', 'Djibouti')");
            Sql("INSERT INTO Countries VALUES ('DM', 'Dominica')");
            Sql("INSERT INTO Countries VALUES ('DO', 'Dominican Republic')");
            Sql("INSERT INTO Countries VALUES ('TP', 'East Timor')");
            Sql("INSERT INTO Countries VALUES ('EC', 'Ecuador')");
            Sql("INSERT INTO Countries VALUES ('EG', 'Egypt')");
            Sql("INSERT INTO Countries VALUES ('SV', 'El Salvador')");
            Sql("INSERT INTO Countries VALUES ('GQ', 'Equatorial Guinea')");
            Sql("INSERT INTO Countries VALUES ('ER', 'Eritrea')");
            Sql("INSERT INTO Countries VALUES ('EE', 'Estonia')");
            Sql("INSERT INTO Countries VALUES ('ET', 'Ethiopia')");
            Sql("INSERT INTO Countries VALUES ('FK', 'Falkland Islands (Malvinas)')");
            Sql("INSERT INTO Countries VALUES ('FO', 'Faroe Islands')");
            Sql("INSERT INTO Countries VALUES ('FJ', 'Fiji')");
            Sql("INSERT INTO Countries VALUES ('FI', 'Finland')");
            Sql("INSERT INTO Countries VALUES ('FR', 'France')");
            Sql("INSERT INTO Countries VALUES ('FX', 'France, Metropolitan')");
            Sql("INSERT INTO Countries VALUES ('GF', 'French Guiana')");
            Sql("INSERT INTO Countries VALUES ('PF', 'French Polynesia')");
            Sql("INSERT INTO Countries VALUES ('TF', 'French Southern Territories')");
            Sql("INSERT INTO Countries VALUES ('GA', 'Gabon')");
            Sql("INSERT INTO Countries VALUES ('GM', 'Gambia')");
            Sql("INSERT INTO Countries VALUES ('GE', 'Georgia')");
            Sql("INSERT INTO Countries VALUES ('DE', 'Germany')");
            Sql("INSERT INTO Countries VALUES ('GH', 'Ghana')");
            Sql("INSERT INTO Countries VALUES ('GI', 'Gibraltar')");
            Sql("INSERT INTO Countries VALUES ('GK', 'Guernsey')");
            Sql("INSERT INTO Countries VALUES ('GR', 'Greece')");
            Sql("INSERT INTO Countries VALUES ('GL', 'Greenland')");
            Sql("INSERT INTO Countries VALUES ('GD', 'Grenada')");
            Sql("INSERT INTO Countries VALUES ('GP', 'Guadeloupe')");
            Sql("INSERT INTO Countries VALUES ('GU', 'Guam')");
            Sql("INSERT INTO Countries VALUES ('GT', 'Guatemala')");
            Sql("INSERT INTO Countries VALUES ('GN', 'Guinea')");
            Sql("INSERT INTO Countries VALUES ('GW', 'Guinea-Bissau')");
            Sql("INSERT INTO Countries VALUES ('GY', 'Guyana')");
            Sql("INSERT INTO Countries VALUES ('HT', 'Haiti')");
            Sql("INSERT INTO Countries VALUES ('HM', 'Heard and Mc Donald Islands')");
            Sql("INSERT INTO Countries VALUES ('HN', 'Honduras')");
            Sql("INSERT INTO Countries VALUES ('HK', 'Hong Kong')");
            Sql("INSERT INTO Countries VALUES ('HU', 'Hungary')");
            Sql("INSERT INTO Countries VALUES ('IS', 'Iceland')");
            Sql("INSERT INTO Countries VALUES ('IN', 'India')");
            Sql("INSERT INTO Countries VALUES ('IM', 'Isle of Man')");
            Sql("INSERT INTO Countries VALUES ('ID', 'Indonesia')");
            Sql("INSERT INTO Countries VALUES ('IR', 'Iran (Islamic Republic of)')");
            Sql("INSERT INTO Countries VALUES ('IQ', 'Iraq')");
            Sql("INSERT INTO Countries VALUES ('IE', 'Ireland')");
            Sql("INSERT INTO Countries VALUES ('IL', 'Israel')");
            Sql("INSERT INTO Countries VALUES ('IT', 'Italy')");
            Sql("INSERT INTO Countries VALUES ('CI', 'Ivory Coast')");
            Sql("INSERT INTO Countries VALUES ('JE', 'Jersey')");
            Sql("INSERT INTO Countries VALUES ('JM', 'Jamaica')");
            Sql("INSERT INTO Countries VALUES ('JP', 'Japan')");
            Sql("INSERT INTO Countries VALUES ('JO', 'Jordan')");
            Sql("INSERT INTO Countries VALUES ('KZ', 'Kazakhstan')");
            Sql("INSERT INTO Countries VALUES ('KE', 'Kenya')");
            Sql("INSERT INTO Countries VALUES ('KI', 'Kiribati')");
            Sql("INSERT INTO Countries VALUES ('KP', 'Korea, Democratic People''s Republic of')");
            Sql("INSERT INTO Countries VALUES ('KR', 'Korea, Republic of')");
            Sql("INSERT INTO Countries VALUES ('XK', 'Kosovo')");
            Sql("INSERT INTO Countries VALUES ('KW', 'Kuwait')");
            Sql("INSERT INTO Countries VALUES ('KG', 'Kyrgyzstan')");
            Sql("INSERT INTO Countries VALUES ('LA', 'Lao People''s Democratic Republic')");
            Sql("INSERT INTO Countries VALUES ('LV', 'Latvia')");
            Sql("INSERT INTO Countries VALUES ('LB', 'Lebanon')");
            Sql("INSERT INTO Countries VALUES ('LS', 'Lesotho')");
            Sql("INSERT INTO Countries VALUES ('LR', 'Liberia')");
            Sql("INSERT INTO Countries VALUES ('LY', 'Libyan Arab Jamahiriya')");
            Sql("INSERT INTO Countries VALUES ('LI', 'Liechtenstein')");
            Sql("INSERT INTO Countries VALUES ('LT', 'Lithuania')");
            Sql("INSERT INTO Countries VALUES ('LU', 'Luxembourg')");
            Sql("INSERT INTO Countries VALUES ('MO', 'Macau')");
            Sql("INSERT INTO Countries VALUES ('MK', 'Macedonia')");
            Sql("INSERT INTO Countries VALUES ('MG', 'Madagascar')");
            Sql("INSERT INTO Countries VALUES ('MW', 'Malawi')");
            Sql("INSERT INTO Countries VALUES ('MY', 'Malaysia')");
            Sql("INSERT INTO Countries VALUES ('MV', 'Maldives')");
            Sql("INSERT INTO Countries VALUES ('ML', 'Mali')");
            Sql("INSERT INTO Countries VALUES ('MT', 'Malta')");
            Sql("INSERT INTO Countries VALUES ('MH', 'Marshall Islands')");
            Sql("INSERT INTO Countries VALUES ('MQ', 'Martinique')");
            Sql("INSERT INTO Countries VALUES ('MR', 'Mauritania')");
            Sql("INSERT INTO Countries VALUES ('MU', 'Mauritius')");
            Sql("INSERT INTO Countries VALUES ('TY', 'Mayotte')");
            Sql("INSERT INTO Countries VALUES ('MX', 'Mexico')");
            Sql("INSERT INTO Countries VALUES ('FM', 'Micronesia, Federated States of')");
            Sql("INSERT INTO Countries VALUES ('MD', 'Moldova, Republic of')");
            Sql("INSERT INTO Countries VALUES ('MC', 'Monaco')");
            Sql("INSERT INTO Countries VALUES ('MN', 'Mongolia')");
            Sql("INSERT INTO Countries VALUES ('ME', 'Montenegro')");
            Sql("INSERT INTO Countries VALUES ('MS', 'Montserrat')");
            Sql("INSERT INTO Countries VALUES ('MA', 'Morocco')");
            Sql("INSERT INTO Countries VALUES ('MZ', 'Mozambique')");
            Sql("INSERT INTO Countries VALUES ('MM', 'Myanmar')");
            Sql("INSERT INTO Countries VALUES ('NA', 'Namibia')");
            Sql("INSERT INTO Countries VALUES ('NR', 'Nauru')");
            Sql("INSERT INTO Countries VALUES ('NP', 'Nepal')");
            Sql("INSERT INTO Countries VALUES ('NL', 'Netherlands')");
            Sql("INSERT INTO Countries VALUES ('AN', 'Netherlands Antilles')");
            Sql("INSERT INTO Countries VALUES ('NC', 'New Caledonia')");
            Sql("INSERT INTO Countries VALUES ('NZ', 'New Zealand')");
            Sql("INSERT INTO Countries VALUES ('NI', 'Nicaragua')");
            Sql("INSERT INTO Countries VALUES ('NE', 'Niger')");
            Sql("INSERT INTO Countries VALUES ('NG', 'Nigeria')");
            Sql("INSERT INTO Countries VALUES ('NU', 'Niue')");
            Sql("INSERT INTO Countries VALUES ('NF', 'Norfolk Island')");
            Sql("INSERT INTO Countries VALUES ('MP', 'Northern Mariana Islands')");
            Sql("INSERT INTO Countries VALUES ('NO', 'Norway')");
            Sql("INSERT INTO Countries VALUES ('OM', 'Oman')");
            Sql("INSERT INTO Countries VALUES ('PK', 'Pakistan')");
            Sql("INSERT INTO Countries VALUES ('PW', 'Palau')");
            Sql("INSERT INTO Countries VALUES ('PS', 'Palestine')");
            Sql("INSERT INTO Countries VALUES ('PA', 'Panama')");
            Sql("INSERT INTO Countries VALUES ('PG', 'Papua New Guinea')");
            Sql("INSERT INTO Countries VALUES ('PY', 'Paraguay')");
            Sql("INSERT INTO Countries VALUES ('PE', 'Peru')");
            Sql("INSERT INTO Countries VALUES ('PH', 'Philippines')");
            Sql("INSERT INTO Countries VALUES ('PN', 'Pitcairn')");
            Sql("INSERT INTO Countries VALUES ('PL', 'Poland')");
            Sql("INSERT INTO Countries VALUES ('PT', 'Portugal')");
            Sql("INSERT INTO Countries VALUES ('PR', 'Puerto Rico')");
            Sql("INSERT INTO Countries VALUES ('QA', 'Qatar')");
            Sql("INSERT INTO Countries VALUES ('RE', 'Reunion')");
            Sql("INSERT INTO Countries VALUES ('RO', 'Romania')");
            Sql("INSERT INTO Countries VALUES ('RU', 'Russian Federation')");
            Sql("INSERT INTO Countries VALUES ('RW', 'Rwanda')");
            Sql("INSERT INTO Countries VALUES ('KN', 'Saint Kitts and Nevis')");
            Sql("INSERT INTO Countries VALUES ('LC', 'Saint Lucia')");
            Sql("INSERT INTO Countries VALUES ('VC', 'Saint Vincent and the Grenadines')");
            Sql("INSERT INTO Countries VALUES ('WS', 'Samoa')");
            Sql("INSERT INTO Countries VALUES ('SM', 'San Marino')");
            Sql("INSERT INTO Countries VALUES ('ST', 'Sao Tome and Principe')");
            Sql("INSERT INTO Countries VALUES ('SA', 'Saudi Arabia')");
            Sql("INSERT INTO Countries VALUES ('SN', 'Senegal')");
            Sql("INSERT INTO Countries VALUES ('RS', 'Serbia')");
            Sql("INSERT INTO Countries VALUES ('SC', 'Seychelles')");
            Sql("INSERT INTO Countries VALUES ('SL', 'Sierra Leone')");
            Sql("INSERT INTO Countries VALUES ('SG', 'Singapore')");
            Sql("INSERT INTO Countries VALUES ('SK', 'Slovakia')");
            Sql("INSERT INTO Countries VALUES ('SI', 'Slovenia')");
            Sql("INSERT INTO Countries VALUES ('SB', 'Solomon Islands')");
            Sql("INSERT INTO Countries VALUES ('SO', 'Somalia')");
            Sql("INSERT INTO Countries VALUES ('ZA', 'South Africa')");
            Sql("INSERT INTO Countries VALUES ('GS', 'South Georgia South Sandwich Islands')");
            Sql("INSERT INTO Countries VALUES ('SS', 'South Sudan')");
            Sql("INSERT INTO Countries VALUES ('ES', 'Spain')");
            Sql("INSERT INTO Countries VALUES ('LK', 'Sri Lanka')");
            Sql("INSERT INTO Countries VALUES ('SH', 'St. Helena')");
            Sql("INSERT INTO Countries VALUES ('PM', 'St. Pierre and Miquelon')");
            Sql("INSERT INTO Countries VALUES ('SD', 'Sudan')");
            Sql("INSERT INTO Countries VALUES ('SR', 'Suriname')");
            Sql("INSERT INTO Countries VALUES ('SJ', 'Svalbard and Jan Mayen Islands')");
            Sql("INSERT INTO Countries VALUES ('SZ', 'Swaziland')");
            Sql("INSERT INTO Countries VALUES ('SE', 'Sweden')");
            Sql("INSERT INTO Countries VALUES ('CH', 'Switzerland')");
            Sql("INSERT INTO Countries VALUES ('SY', 'Syrian Arab Republic')");
            Sql("INSERT INTO Countries VALUES ('TW', 'Taiwan')");
            Sql("INSERT INTO Countries VALUES ('TJ', 'Tajikistan')");
            Sql("INSERT INTO Countries VALUES ('TZ', 'Tanzania, United Republic of')");
            Sql("INSERT INTO Countries VALUES ('TH', 'Thailand')");
            Sql("INSERT INTO Countries VALUES ('TG', 'Togo')");
            Sql("INSERT INTO Countries VALUES ('TK', 'Tokelau')");
            Sql("INSERT INTO Countries VALUES ('TO', 'Tonga')");
            Sql("INSERT INTO Countries VALUES ('TT', 'Trinidad and Tobago')");
            Sql("INSERT INTO Countries VALUES ('TN', 'Tunisia')");
            Sql("INSERT INTO Countries VALUES ('TR', 'Turkey')");
            Sql("INSERT INTO Countries VALUES ('TM', 'Turkmenistan')");
            Sql("INSERT INTO Countries VALUES ('TC', 'Turks and Caicos Islands')");
            Sql("INSERT INTO Countries VALUES ('TV', 'Tuvalu')");
            Sql("INSERT INTO Countries VALUES ('UG', 'Uganda')");
            Sql("INSERT INTO Countries VALUES ('UA', 'Ukraine')");
            Sql("INSERT INTO Countries VALUES ('AE', 'United Arab Emirates')");
            Sql("INSERT INTO Countries VALUES ('GB', 'United Kingdom')");
            Sql("INSERT INTO Countries VALUES ('US', 'United States')");
            Sql("INSERT INTO Countries VALUES ('UM', 'United States minor outlying islands')");
            Sql("INSERT INTO Countries VALUES ('UY', 'Uruguay')");
            Sql("INSERT INTO Countries VALUES ('UZ', 'Uzbekistan')");
            Sql("INSERT INTO Countries VALUES ('VU', 'Vanuatu')");
            Sql("INSERT INTO Countries VALUES ('VA', 'Vatican City State')");
            Sql("INSERT INTO Countries VALUES ('VE', 'Venezuela')");
            Sql("INSERT INTO Countries VALUES ('VN', 'Vietnam')");
            Sql("INSERT INTO Countries VALUES ('VG', 'Virgin Islands (British)')");
            Sql("INSERT INTO Countries VALUES ('VI', 'Virgin Islands (U.S.)')");
            Sql("INSERT INTO Countries VALUES ('WF', 'Wallis and Futuna Islands')");
            Sql("INSERT INTO Countries VALUES ('EH', 'Western Sahara')");
            Sql("INSERT INTO Countries VALUES ('YE', 'Yemen')");
            Sql("INSERT INTO Countries VALUES ('ZR', 'Zaire')");
            Sql("INSERT INTO Countries VALUES ('ZM', 'Zambia')");
            Sql("INSERT INTO Countries VALUES ('ZW', 'Zimbabwe')");


        }

        public override void Down()
        {
        }
    }
}
