namespace Quadridge2.Migrations
{
  using System;
  using System.Data.Entity.Migrations;

  public partial class populateCountries : DbMigration
  {
    public override void Up()
    {
      Sql("INSERT INTO Countries (Code, Name)  VALUES ('AF', 'Afghanistan')");
      Sql("INSERT INTO Countries (Code, Name)  VALUES ('AL', 'Albania')");
      Sql("INSERT INTO Countries (Code, Name)  VALUES ('DZ', 'Algeria')");
      Sql("INSERT INTO Countries (Code, Name)  VALUES ('DS', 'American Samoa')");
      Sql("INSERT INTO Countries (Code, Name)  VALUES ('AD', 'Andorra')");
      Sql("INSERT INTO Countries (Code, Name)  VALUES ('AO', 'Angola')");
      Sql("INSERT INTO Countries (Code, Name)  VALUES ('AI', 'Anguilla')");
      Sql("INSERT INTO Countries (Code, Name)  VALUES ('AQ', 'Antarctica')");
      Sql("INSERT INTO Countries (Code, Name)  VALUES ('AG', 'Antigua and Barbuda')");
      Sql("INSERT INTO Countries (Code, Name)  VALUES ('AR', 'Argentina')");
      Sql("INSERT INTO Countries (Code, Name)  VALUES ('AM', 'Armenia')");
      Sql("INSERT INTO Countries (Code, Name)  VALUES ('AW', 'Aruba')");
      Sql("INSERT INTO Countries (Code, Name)  VALUES ('AU', 'Australia')");
      Sql("INSERT INTO Countries (Code, Name)  VALUES ('AT', 'Austria')");
      Sql("INSERT INTO Countries (Code, Name)  VALUES ('AZ', 'Azerbaijan')");
      Sql("INSERT INTO Countries (Code, Name)  VALUES ('BS', 'Bahamas')");
      Sql("INSERT INTO Countries (Code, Name)  VALUES ('BH', 'Bahrain')");
      Sql("INSERT INTO Countries (Code, Name)  VALUES ('BD', 'Bangladesh')");
      Sql("INSERT INTO Countries (Code, Name)  VALUES ('BB', 'Barbados')");
      Sql("INSERT INTO Countries (Code, Name)  VALUES ('BY', 'Belarus')");
      Sql("INSERT INTO Countries (Code, Name)  VALUES ('BE', 'Belgium')");
      Sql("INSERT INTO Countries (Code, Name)  VALUES ('BZ', 'Belize')");
      Sql("INSERT INTO Countries (Code, Name)  VALUES ('BJ', 'Benin')");
      Sql("INSERT INTO Countries (Code, Name)  VALUES ('BM', 'Bermuda')");
      Sql("INSERT INTO Countries (Code, Name)  VALUES ('BT', 'Bhutan')");
      Sql("INSERT INTO Countries (Code, Name)  VALUES ('BO', 'Bolivia')");
      Sql("INSERT INTO Countries (Code, Name)  VALUES ('BA', 'Bosnia and Herzegovina')");
      Sql("INSERT INTO Countries (Code, Name)  VALUES ('BW', 'Botswana')");
      Sql("INSERT INTO Countries (Code, Name)  VALUES ('BV', 'Bouvet Island')");
      Sql("INSERT INTO Countries (Code, Name)  VALUES ('BR', 'Brazil')");
      Sql("INSERT INTO Countries (Code, Name)  VALUES ('IO', 'British Indian Ocean Territory')");
      Sql("INSERT INTO Countries (Code, Name)  VALUES ('BN', 'Brunei Darussalam')");
      Sql("INSERT INTO Countries (Code, Name)  VALUES ('BG', 'Bulgaria')");
      Sql("INSERT INTO Countries (Code, Name)  VALUES ('BF', 'Burkina Faso')");
      Sql("INSERT INTO Countries (Code, Name)  VALUES ('BI', 'Burundi')");
      Sql("INSERT INTO Countries (Code, Name)  VALUES ('KH', 'Cambodia')");
      Sql("INSERT INTO Countries (Code, Name)  VALUES ('CM', 'Cameroon')");
      Sql("INSERT INTO Countries (Code, Name)  VALUES ('CA', 'Canada')");
      Sql("INSERT INTO Countries (Code, Name)  VALUES ('CV', 'Cape Verde')");
      Sql("INSERT INTO Countries (Code, Name)  VALUES ('KY', 'Cayman Islands')");
      Sql("INSERT INTO Countries (Code, Name)  VALUES ('CF', 'Central African Republic')");
      Sql("INSERT INTO Countries (Code, Name)  VALUES ('TD', 'Chad')");
      Sql("INSERT INTO Countries (Code, Name)  VALUES ('CL', 'Chile')");
      Sql("INSERT INTO Countries (Code, Name)  VALUES ('CN', 'China')");
      Sql("INSERT INTO Countries (Code, Name)  VALUES ('CX', 'Christmas Island')");
      Sql("INSERT INTO Countries (Code, Name)  VALUES ('CC', 'Cocos (Keeling) Islands')");
      Sql("INSERT INTO Countries (Code, Name)  VALUES ('CO', 'Colombia')");
      Sql("INSERT INTO Countries (Code, Name)  VALUES ('KM', 'Comoros')");
      Sql("INSERT INTO Countries (Code, Name)  VALUES ('CG', 'Congo')");
      Sql("INSERT INTO Countries (Code, Name)  VALUES ('CK', 'Cook Islands')");
      Sql("INSERT INTO Countries (Code, Name)  VALUES ('CR', 'Costa Rica')");
      Sql("INSERT INTO Countries (Code, Name)  VALUES ('HR', 'Croatia (Hrvatska)')");
      Sql("INSERT INTO Countries (Code, Name)  VALUES ('CU', 'Cuba')");
      Sql("INSERT INTO Countries (Code, Name)  VALUES ('CY', 'Cyprus')");
      Sql("INSERT INTO Countries (Code, Name)  VALUES ('CZ', 'Czech Republic')");
      Sql("INSERT INTO Countries (Code, Name)  VALUES ('DK', 'Denmark')");
      Sql("INSERT INTO Countries (Code, Name)  VALUES ('DJ', 'Djibouti')");
      Sql("INSERT INTO Countries (Code, Name)  VALUES ('DM', 'Dominica')");
      Sql("INSERT INTO Countries (Code, Name)  VALUES ('DO', 'Dominican Republic')");
      Sql("INSERT INTO Countries (Code, Name)  VALUES ('TP', 'East Timor')");
      Sql("INSERT INTO Countries (Code, Name)  VALUES ('EC', 'Ecuador')");
      Sql("INSERT INTO Countries (Code, Name)  VALUES ('EG', 'Egypt')");
      Sql("INSERT INTO Countries (Code, Name)  VALUES ('SV', 'El Salvador')");
      Sql("INSERT INTO Countries (Code, Name)  VALUES ('GQ', 'Equatorial Guinea')");
      Sql("INSERT INTO Countries (Code, Name)  VALUES ('ER', 'Eritrea')");
      Sql("INSERT INTO Countries (Code, Name)  VALUES ('EE', 'Estonia')");
      Sql("INSERT INTO Countries (Code, Name)  VALUES ('ET', 'Ethiopia')");
      Sql("INSERT INTO Countries (Code, Name)  VALUES ('FK', 'Falkland Islands (Malvinas)')");
      Sql("INSERT INTO Countries (Code, Name)  VALUES ('FO', 'Faroe Islands')");
      Sql("INSERT INTO Countries (Code, Name)  VALUES ('FJ', 'Fiji')");
      Sql("INSERT INTO Countries (Code, Name)  VALUES ('FI', 'Finland')");
      Sql("INSERT INTO Countries (Code, Name)  VALUES ('FR', 'France')");
      Sql("INSERT INTO Countries (Code, Name)  VALUES ('FX', 'France, Metropolitan')");
      Sql("INSERT INTO Countries (Code, Name)  VALUES ('GF', 'French Guiana')");
      Sql("INSERT INTO Countries (Code, Name)  VALUES ('PF', 'French Polynesia')");
      Sql("INSERT INTO Countries (Code, Name)  VALUES ('TF', 'French Southern Territories')");
      Sql("INSERT INTO Countries (Code, Name)  VALUES ('GA', 'Gabon')");
      Sql("INSERT INTO Countries (Code, Name)  VALUES ('GM', 'Gambia')");
      Sql("INSERT INTO Countries (Code, Name)  VALUES ('GE', 'Georgia')");
      Sql("INSERT INTO Countries (Code, Name)  VALUES ('DE', 'Germany')");
      Sql("INSERT INTO Countries (Code, Name)  VALUES ('GH', 'Ghana')");
      Sql("INSERT INTO Countries (Code, Name)  VALUES ('GI', 'Gibraltar')");
      Sql("INSERT INTO Countries (Code, Name)  VALUES ('GK', 'Guernsey')");
      Sql("INSERT INTO Countries (Code, Name)  VALUES ('GR', 'Greece')");
      Sql("INSERT INTO Countries (Code, Name)  VALUES ('GL', 'Greenland')");
      Sql("INSERT INTO Countries (Code, Name)  VALUES ('GD', 'Grenada')");
      Sql("INSERT INTO Countries (Code, Name)  VALUES ('GP', 'Guadeloupe')");
      Sql("INSERT INTO Countries (Code, Name)  VALUES ('GU', 'Guam')");
      Sql("INSERT INTO Countries (Code, Name)  VALUES ('GT', 'Guatemala')");
      Sql("INSERT INTO Countries (Code, Name)  VALUES ('GN', 'Guinea')");
      Sql("INSERT INTO Countries (Code, Name)  VALUES ('GW', 'Guinea-Bissau')");
      Sql("INSERT INTO Countries (Code, Name)  VALUES ('GY', 'Guyana')");
      Sql("INSERT INTO Countries (Code, Name)  VALUES ('HT', 'Haiti')");
      Sql("INSERT INTO Countries (Code, Name)  VALUES ('HM', 'Heard and Mc Donald Islands')");
      Sql("INSERT INTO Countries (Code, Name)  VALUES ('HN', 'Honduras')");
      Sql("INSERT INTO Countries (Code, Name)  VALUES ('HK', 'Hong Kong')");
      Sql("INSERT INTO Countries (Code, Name)  VALUES ('HU', 'Hungary')");
      Sql("INSERT INTO Countries (Code, Name)  VALUES ('IS', 'Iceland')");
      Sql("INSERT INTO Countries (Code, Name)  VALUES ('IN', 'India')");
      Sql("INSERT INTO Countries (Code, Name)  VALUES ('IM', 'Isle of Man')");
      Sql("INSERT INTO Countries (Code, Name)  VALUES ('ID', 'Indonesia')");
      Sql("INSERT INTO Countries (Code, Name)  VALUES ('IR', 'Iran (Islamic Republic of)')");
      Sql("INSERT INTO Countries (Code, Name)  VALUES ('IQ', 'Iraq')");
      Sql("INSERT INTO Countries (Code, Name)  VALUES ('IE', 'Ireland')");
      Sql("INSERT INTO Countries (Code, Name)  VALUES ('IL', 'Israel')");
      Sql("INSERT INTO Countries (Code, Name)  VALUES ('IT', 'Italy')");
      Sql("INSERT INTO Countries (Code, Name)  VALUES ('CI', 'Ivory Coast')");
      Sql("INSERT INTO Countries (Code, Name)  VALUES ('JE', 'Jersey')");
      Sql("INSERT INTO Countries (Code, Name)  VALUES ('JM', 'Jamaica')");
      Sql("INSERT INTO Countries (Code, Name)  VALUES ('JP', 'Japan')");
      Sql("INSERT INTO Countries (Code, Name)  VALUES ('JO', 'Jordan')");
      Sql("INSERT INTO Countries (Code, Name)  VALUES ('KZ', 'Kazakhstan')");
      Sql("INSERT INTO Countries (Code, Name)  VALUES ('KE', 'Kenya')");
      Sql("INSERT INTO Countries (Code, Name)  VALUES ('KI', 'Kiribati')");
      Sql("INSERT INTO Countries (Code, Name)  VALUES ('KP', 'Korea, Democratic People''s Republic of')");
      Sql("INSERT INTO Countries (Code, Name)  VALUES ('KR', 'Korea, Republic of')");
      Sql("INSERT INTO Countries (Code, Name)  VALUES ('XK', 'Kosovo')");
      Sql("INSERT INTO Countries (Code, Name)  VALUES ('KW', 'Kuwait')");
      Sql("INSERT INTO Countries (Code, Name)  VALUES ('KG', 'Kyrgyzstan')");
      Sql("INSERT INTO Countries (Code, Name)  VALUES ('LA', 'Lao People''s Democratic Republic')");
      Sql("INSERT INTO Countries (Code, Name)  VALUES ('LV', 'Latvia')");
      Sql("INSERT INTO Countries (Code, Name)  VALUES ('LB', 'Lebanon')");
      Sql("INSERT INTO Countries (Code, Name)  VALUES ('LS', 'Lesotho')");
      Sql("INSERT INTO Countries (Code, Name)  VALUES ('LR', 'Liberia')");
      Sql("INSERT INTO Countries (Code, Name)  VALUES ('LY', 'Libyan Arab Jamahiriya')");
      Sql("INSERT INTO Countries (Code, Name)  VALUES ('LI', 'Liechtenstein')");
      Sql("INSERT INTO Countries (Code, Name)  VALUES ('LT', 'Lithuania')");
      Sql("INSERT INTO Countries (Code, Name)  VALUES ('LU', 'Luxembourg')");
      Sql("INSERT INTO Countries (Code, Name)  VALUES ('MO', 'Macau')");
      Sql("INSERT INTO Countries (Code, Name)  VALUES ('MK', 'Macedonia')");
      Sql("INSERT INTO Countries (Code, Name)  VALUES ('MG', 'Madagascar')");
      Sql("INSERT INTO Countries (Code, Name)  VALUES ('MW', 'Malawi')");
      Sql("INSERT INTO Countries (Code, Name)  VALUES ('MY', 'Malaysia')");
      Sql("INSERT INTO Countries (Code, Name)  VALUES ('MV', 'Maldives')");
      Sql("INSERT INTO Countries (Code, Name)  VALUES ('ML', 'Mali')");
      Sql("INSERT INTO Countries (Code, Name)  VALUES ('MT', 'Malta')");
      Sql("INSERT INTO Countries (Code, Name)  VALUES ('MH', 'Marshall Islands')");
      Sql("INSERT INTO Countries (Code, Name)  VALUES ('MQ', 'Martinique')");
      Sql("INSERT INTO Countries (Code, Name)  VALUES ('MR', 'Mauritania')");
      Sql("INSERT INTO Countries (Code, Name)  VALUES ('MU', 'Mauritius')");
      Sql("INSERT INTO Countries (Code, Name)  VALUES ('TY', 'Mayotte')");
      Sql("INSERT INTO Countries (Code, Name)  VALUES ('MX', 'Mexico')");
      Sql("INSERT INTO Countries (Code, Name)  VALUES ('FM', 'Micronesia, Federated States of')");
      Sql("INSERT INTO Countries (Code, Name)  VALUES ('MD', 'Moldova, Republic of')");
      Sql("INSERT INTO Countries (Code, Name)  VALUES ('MC', 'Monaco')");
      Sql("INSERT INTO Countries (Code, Name)  VALUES ('MN', 'Mongolia')");
      Sql("INSERT INTO Countries (Code, Name)  VALUES ('ME', 'Montenegro')");
      Sql("INSERT INTO Countries (Code, Name)  VALUES ('MS', 'Montserrat')");
      Sql("INSERT INTO Countries (Code, Name)  VALUES ('MA', 'Morocco')");
      Sql("INSERT INTO Countries (Code, Name)  VALUES ('MZ', 'Mozambique')");
      Sql("INSERT INTO Countries (Code, Name)  VALUES ('MM', 'Myanmar')");
      Sql("INSERT INTO Countries (Code, Name)  VALUES ('NA', 'Namibia')");
      Sql("INSERT INTO Countries (Code, Name)  VALUES ('NR', 'Nauru')");
      Sql("INSERT INTO Countries (Code, Name)  VALUES ('NP', 'Nepal')");
      Sql("INSERT INTO Countries (Code, Name)  VALUES ('NL', 'Netherlands')");
      Sql("INSERT INTO Countries (Code, Name)  VALUES ('AN', 'Netherlands Antilles')");
      Sql("INSERT INTO Countries (Code, Name)  VALUES ('NC', 'New Caledonia')");
      Sql("INSERT INTO Countries (Code, Name)  VALUES ('NZ', 'New Zealand')");
      Sql("INSERT INTO Countries (Code, Name)  VALUES ('NI', 'Nicaragua')");
      Sql("INSERT INTO Countries (Code, Name)  VALUES ('NE', 'Niger')");
      Sql("INSERT INTO Countries (Code, Name)  VALUES ('NG', 'Nigeria')");
      Sql("INSERT INTO Countries (Code, Name)  VALUES ('NU', 'Niue')");
      Sql("INSERT INTO Countries (Code, Name)  VALUES ('NF', 'Norfolk Island')");
      Sql("INSERT INTO Countries (Code, Name)  VALUES ('MP', 'Northern Mariana Islands')");
      Sql("INSERT INTO Countries (Code, Name)  VALUES ('NO', 'Norway')");
      Sql("INSERT INTO Countries (Code, Name)  VALUES ('OM', 'Oman')");
      Sql("INSERT INTO Countries (Code, Name)  VALUES ('PK', 'Pakistan')");
      Sql("INSERT INTO Countries (Code, Name)  VALUES ('PW', 'Palau')");
      Sql("INSERT INTO Countries (Code, Name)  VALUES ('PS', 'Palestine')");
      Sql("INSERT INTO Countries (Code, Name)  VALUES ('PA', 'Panama')");
      Sql("INSERT INTO Countries (Code, Name)  VALUES ('PG', 'Papua New Guinea')");
      Sql("INSERT INTO Countries (Code, Name)  VALUES ('PY', 'Paraguay')");
      Sql("INSERT INTO Countries (Code, Name)  VALUES ('PE', 'Peru')");
      Sql("INSERT INTO Countries (Code, Name)  VALUES ('PH', 'Philippines')");
      Sql("INSERT INTO Countries (Code, Name)  VALUES ('PN', 'Pitcairn')");
      Sql("INSERT INTO Countries (Code, Name)  VALUES ('PL', 'Poland')");
      Sql("INSERT INTO Countries (Code, Name)  VALUES ('PT', 'Portugal')");
      Sql("INSERT INTO Countries (Code, Name)  VALUES ('PR', 'Puerto Rico')");
      Sql("INSERT INTO Countries (Code, Name)  VALUES ('QA', 'Qatar')");
      Sql("INSERT INTO Countries (Code, Name)  VALUES ('RE', 'Reunion')");
      Sql("INSERT INTO Countries (Code, Name)  VALUES ('RO', 'Romania')");
      Sql("INSERT INTO Countries (Code, Name)  VALUES ('RU', 'Russian Federation')");
      Sql("INSERT INTO Countries (Code, Name)  VALUES ('RW', 'Rwanda')");
      Sql("INSERT INTO Countries (Code, Name)  VALUES ('KN', 'Saint Kitts and Nevis')");
      Sql("INSERT INTO Countries (Code, Name)  VALUES ('LC', 'Saint Lucia')");
      Sql("INSERT INTO Countries (Code, Name)  VALUES ('VC', 'Saint Vincent and the Grenadines')");
      Sql("INSERT INTO Countries (Code, Name)  VALUES ('WS', 'Samoa')");
      Sql("INSERT INTO Countries (Code, Name)  VALUES ('SM', 'San Marino')");
      Sql("INSERT INTO Countries (Code, Name)  VALUES ('ST', 'Sao Tome and Principe')");
      Sql("INSERT INTO Countries (Code, Name)  VALUES ('SA', 'Saudi Arabia')");
      Sql("INSERT INTO Countries (Code, Name)  VALUES ('SN', 'Senegal')");
      Sql("INSERT INTO Countries (Code, Name)  VALUES ('RS', 'Serbia')");
      Sql("INSERT INTO Countries (Code, Name)  VALUES ('SC', 'Seychelles')");
      Sql("INSERT INTO Countries (Code, Name)  VALUES ('SL', 'Sierra Leone')");
      Sql("INSERT INTO Countries (Code, Name)  VALUES ('SG', 'Singapore')");
      Sql("INSERT INTO Countries (Code, Name)  VALUES ('SK', 'Slovakia')");
      Sql("INSERT INTO Countries (Code, Name)  VALUES ('SI', 'Slovenia')");
      Sql("INSERT INTO Countries (Code, Name)  VALUES ('SB', 'Solomon Islands')");
      Sql("INSERT INTO Countries (Code, Name)  VALUES ('SO', 'Somalia')");
      Sql("INSERT INTO Countries (Code, Name)  VALUES ('ZA', 'South Africa')");
      Sql("INSERT INTO Countries (Code, Name)  VALUES ('GS', 'South Georgia South Sandwich Islands')");
      Sql("INSERT INTO Countries (Code, Name)  VALUES ('SS', 'South Sudan')");
      Sql("INSERT INTO Countries (Code, Name)  VALUES ('ES', 'Spain')");
      Sql("INSERT INTO Countries (Code, Name)  VALUES ('LK', 'Sri Lanka')");
      Sql("INSERT INTO Countries (Code, Name)  VALUES ('SH', 'St. Helena')");
      Sql("INSERT INTO Countries (Code, Name)  VALUES ('PM', 'St. Pierre and Miquelon')");
      Sql("INSERT INTO Countries (Code, Name)  VALUES ('SD', 'Sudan')");
      Sql("INSERT INTO Countries (Code, Name)  VALUES ('SR', 'Suriname')");
      Sql("INSERT INTO Countries (Code, Name)  VALUES ('SJ', 'Svalbard and Jan Mayen Islands')");
      Sql("INSERT INTO Countries (Code, Name)  VALUES ('SZ', 'Swaziland')");
      Sql("INSERT INTO Countries (Code, Name)  VALUES ('SE', 'Sweden')");
      Sql("INSERT INTO Countries (Code, Name)  VALUES ('CH', 'Switzerland')");
      Sql("INSERT INTO Countries (Code, Name)  VALUES ('SY', 'Syrian Arab Republic')");
      Sql("INSERT INTO Countries (Code, Name)  VALUES ('TW', 'Taiwan')");
      Sql("INSERT INTO Countries (Code, Name)  VALUES ('TJ', 'Tajikistan')");
      Sql("INSERT INTO Countries (Code, Name)  VALUES ('TZ', 'Tanzania, United Republic of')");
      Sql("INSERT INTO Countries (Code, Name)  VALUES ('TH', 'Thailand')");
      Sql("INSERT INTO Countries (Code, Name)  VALUES ('TG', 'Togo')");
      Sql("INSERT INTO Countries (Code, Name)  VALUES ('TK', 'Tokelau')");
      Sql("INSERT INTO Countries (Code, Name)  VALUES ('TO', 'Tonga')");
      Sql("INSERT INTO Countries (Code, Name)  VALUES ('TT', 'Trinidad and Tobago')");
      Sql("INSERT INTO Countries (Code, Name)  VALUES ('TN', 'Tunisia')");
      Sql("INSERT INTO Countries (Code, Name)  VALUES ('TR', 'Turkey')");
      Sql("INSERT INTO Countries (Code, Name)  VALUES ('TM', 'Turkmenistan')");
      Sql("INSERT INTO Countries (Code, Name)  VALUES ('TC', 'Turks and Caicos Islands')");
      Sql("INSERT INTO Countries (Code, Name)  VALUES ('TV', 'Tuvalu')");
      Sql("INSERT INTO Countries (Code, Name)  VALUES ('UG', 'Uganda')");
      Sql("INSERT INTO Countries (Code, Name)  VALUES ('UA', 'Ukraine')");
      Sql("INSERT INTO Countries (Code, Name)  VALUES ('AE', 'United Arab Emirates')");
      Sql("INSERT INTO Countries (Code, Name)  VALUES ('GB', 'United Kingdom')");
      Sql("INSERT INTO Countries (Code, Name)  VALUES ('US', 'United States')");
      Sql("INSERT INTO Countries (Code, Name)  VALUES ('UM', 'United States minor outlying islands')");
      Sql("INSERT INTO Countries (Code, Name)  VALUES ('UY', 'Uruguay')");
      Sql("INSERT INTO Countries (Code, Name)  VALUES ('UZ', 'Uzbekistan')");
      Sql("INSERT INTO Countries (Code, Name)  VALUES ('VU', 'Vanuatu')");
      Sql("INSERT INTO Countries (Code, Name)  VALUES ('VA', 'Vatican City State')");
      Sql("INSERT INTO Countries (Code, Name)  VALUES ('VE', 'Venezuela')");
      Sql("INSERT INTO Countries (Code, Name)  VALUES ('VN', 'Vietnam')");
      Sql("INSERT INTO Countries (Code, Name)  VALUES ('VG', 'Virgin Islands (British)')");
      Sql("INSERT INTO Countries (Code, Name)  VALUES ('VI', 'Virgin Islands (U.S.)')");
      Sql("INSERT INTO Countries (Code, Name)  VALUES ('WF', 'Wallis and Futuna Islands')");
      Sql("INSERT INTO Countries (Code, Name)  VALUES ('EH', 'Western Sahara')");
      Sql("INSERT INTO Countries (Code, Name)  VALUES ('YE', 'Yemen')");
      Sql("INSERT INTO Countries (Code, Name)  VALUES ('ZR', 'Zaire')");
      Sql("INSERT INTO Countries (Code, Name)  VALUES ('ZM', 'Zambia')");
      Sql("INSERT INTO Countries (Code, Name)  VALUES ('ZW', 'Zimbabwe')");
    }

    public override void Down()
    {
    }
  }
}
